{
 "title": "Powerwall Simple",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Live Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Energy Usage",
   "type": "graph",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Home Usage",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "http",
     "query": "SELECT \"mean_load_instant_power\" FROM \"http\" WHERE $timeFilter tz('America/Los_Angeles')",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "America/Los_Angeles"
    },
    {
     "alias": "Solar Energy",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "America/Los_Angeles"
    },
    {
     "alias": "Powerwall",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "http",
     "query": "SELECT mean(from_pw) - mean(to_pw) FROM autogen.http WHERE $timeFilter GROUP BY time(5m) tz('America/Los_Angeles')",
     "select": [
      [
       { "params": [ "from_pw+to_pw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "America/Los_Angeles"
    },
    {
     "alias": "Grid Usage",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(from_grid) - mean(to_grid) FROM autogen.http WHERE $timeFilter GROUP BY time(5m) tz('America/Los_Angeles')",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "America/Los_Angeles"
    },
    {
     "alias": "Charge",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT \"mean_percentage\" FROM \"http\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /0.95 - 5/0.95" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    },
    { "target": "sun_altitude" }
   ]
  },
  {
   "title": "Powerwall",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       { "params": [ " /0.95 - 5/0.95" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "Self-powered",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 4 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "alias": "From Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  (1+from_solar/abs(from_solar))*from_solar/2  FROM (SELECT integral(solar)/1000/3600 - integral(to_pw)/1000/3600 - integral(to_grid)/1000/3600  AS from_solar FROM autogen.http WHERE  $timeFilter tz('America/Los_Angeles'))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "From Powerwall",
     "measurement": "http",
     "select": [
      [
       { "params": [ "from_pw" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    },
    {
     "alias": "From Grid",
     "measurement": "http",
     "select": [
      [
       { "params": [ "from_grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "Savings",
   "type": "graph",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 11 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "powerwall > home",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT fp FROM (SELECT sum(\"from_pw\")  * 0.19 AS fp FROM kwh.http WHERE  $timeFilter tz('America/Los_Angeles'))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solar > home",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT s - (tp + tg) FROM (SELECT sum(\"solar\") * 0.19 AS s,  sum(\"to_pw\")  * 0.19 AS tp, sum(\"to_grid\") * 0.19 AS tg FROM kwh.http WHERE  $timeFilter tz('America/Los_Angeles'))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "solar > grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT tg FROM (SELECT sum(\"to_pw\")  * 0.19 AS tp, sum(\"solar\") * 0.19 AS s, sum(\"to_grid\") * 0.19 AS tg FROM kwh.http WHERE  $timeFilter tz('America/Los_Angeles'))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "total",
     "query": "SELECT tg + (s - tp - tg ) + fp FROM (SELECT sum(\"to_pw\")  * 0.19 AS tp, sum(\"solar\") * 0.19 AS s, sum(\"to_grid\") * 0.19 AS tg, sum(\"from_pw\") * 0.19 AS fp FROM kwh.http WHERE  $timeFilter tz('America/Los_Angeles'))\n"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "SELECT last(\"battery_instant_power\")  / 1000 AS \"Powerwall\", last(\"solar_instant_power\")  / 1000 AS \"Solar\", last(\"load_instant_power\")  / 1000 AS \"Home\", last(\"site_instant_power\")  / 1000 AS \"Grid\" FROM \"raw\".\"http\" WHERE time >= now() - 1m"
    }
   ]
  },
  {
   "title": "Home Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "From Powerwall",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "from_pw" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "From Grid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "from_grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "Solar Energy",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "To Powerwall",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "to_pw" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "To Grid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "to_grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "Monthly Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Home Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Home Usage",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "Solar Energy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Solar Energy",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "solar", "operator": ">", "value": "0" }
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "From Powerwall",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "From Powerwall",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "from_pw" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "Grid Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "From Grid",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "from_grid" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "America/Los_Angeles"
    },
    {
     "alias": "To Grid",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "to_grid" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  },
  {
   "title": "Solar Energy Year",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Solar Energy Year",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "solar", "operator": ">", "value": "0" }
     ],
     "tz": "America/Los_Angeles"
    }
   ]
  }
 ]
}