services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        hostname: influxdb
        restart: unless-stopped
        network_mode: host
        volumes:
            - type: bind
              source: ./influxdb.conf
              target: /etc/influxdb/influxdb.conf
              read_only: true
            - type: bind
              source: ./influxdb
              target: /var/lib/influxdb
        env_file:
            - influxdb.env

    pypowerwall:
        image: jasonacox/pypowerwall:0.12.3.t68
        container_name: pypowerwall
        hostname: pypowerwall
        restart: unless-stopped
        volumes:
            - type: bind
              source: .auth
              target: /app/.auth
        user: "${PWD_USER:-1000:1000}"
        network_mode: host
        environment:
            - PW_AUTH_PATH_1=.auth
            - PW_AUTH_PATH_2=.auth
        env_file:
            - pypowerwall.env

    telegraf:
        image: telegraf:1.28.2
        container_name: telegraf
        hostname: telegraf
        restart: unless-stopped
        user: "${PWD_USER:-1000:1000}"
        network_mode: host
        command: [
            "telegraf",
            "--config",
            "/etc/telegraf/telegraf.conf",
            "--config-directory",
            "/etc/telegraf/telegraf.d"
        ]
        volumes:
            - type: bind
              source: ./telegraf.conf
              target: /etc/telegraf/telegraf.conf
              read_only: true
            - type: bind
              source: ./telegraf.local
              target: /etc/telegraf/telegraf.d/local.conf
              read_only: true
            - type: bind
              source: ./VERSION
              target: /etc/telegraf/VERSION
              read_only: true
            - type: bind
              source: ./ver.sh
              target: /etc/telegraf/ver.sh
              read_only: true
        depends_on:
            - influxdb
            - pypowerwall

    grafana:
        image: grafana/grafana:9.1.2-ubuntu
        container_name: grafana
        hostname: grafana
        restart: unless-stopped
        user: "${PWD_USER:-1000:1000}"
        network_mode: host
        volumes:
            - type: bind
              source: ./grafana
              target: /var/lib/grafana
        env_file:
            - grafana.env
        depends_on:
            - influxdb

    weather411:
        image: jasonacox/weather411:0.2.3
        container_name: weather411
        hostname: weather411
        restart: unless-stopped
        user: "${PWD_USER:-1000:1000}"
        network_mode: host
        volumes:
            - type: bind
              source: ./weather
              target: /var/lib/weather
              read_only: true
        environment:
            - WEATHERCONF=/var/lib/weather/weather411.conf
        depends_on:
            - influxdb
