version: "3.5"

services:
    influxdb:
        image: influxdb:1.8
        container_name: influxdb
        hostname: influxdb
        restart: always
        volumes:
            - type: bind
              source: ./influxdb.conf
              target: /etc/influxdb/influxdb.conf
              read_only: true
            - type: bind
              source: ./influxdb
              target: /var/lib/influxdb
        ports:
            - target: 8086
              published: 8086
              mode: host

    pypowerwall:
        image: jasonacox/pypowerwall:latest
        container_name: pypowerwall
        hostname: pypowerwall
        restart: always
        ports:
            - target: 8675
              published: 8675
              mode: host
        env_file:
            - pypowerwall.env

    telegraf:
        image: telegraf:latest
        container_name: telegraf
        hostname: telegraf
        restart: always
        volumes:
            - type: bind
              source: ./telegraf.conf
              target: /etc/telegraf/telegraf.conf
              read_only: true
        depends_on:
            - influxdb
            - pypowerwall

    grafana:
        image: grafana/grafana:6.5.1-ubuntu
        container_name: grafana
        hostname: grafana
        restart: always
        user: "1000:1000"
        volumes:
            - type: bind
              source: ./grafana
              target: /var/lib/grafana
        ports:
            - target: 9000
              published: 9000
              mode: host
        environment:
            - grafana.env
        depends_on:
            - influxdb

