apiVersion: 1

datasources:
  - name: InfluxDB (auto provisioned)
    type: influxdb
    access: proxy
    url: http://localhost:8086
    database: powerwall
    jsonData:
      dbName: powerwall
      timeInterval: 5s
