{
 "title": "Tesla Energy",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "kWhCost", "label": "kWh Cost", "query": ".37" }
  ]
 },
 "panels": [
  { "title": "Live Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy Use",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"home\" or r[\"_field\"] == \"solar\" or r[\"_field\"] == \"grid\" or r[\"_field\"] == \"powerwall\" or r[\"_field\"] ==  \"backup_reserve_percent\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"percentage\")\r\n  |> map(fn: (r) => ({r with _value: (r._value / 0.95) - 5.0 / 0.95 }))\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    },
    { "target": [ "sun_altitude" ] },
    {
     "query": "from(bucket: \"raw_weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"clouds\" or r[\"_field\"] == \"feels_like\" or r[\"_field\"] == \"temperature\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Power Flow",
   "type": "text",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "options": {
    "content": "<style>\ndiv.powerDiv {\n      width: 100%;\n      height: 100%;\n      overflow: hidden;\n    }\ndiv.firmwareDiv {\n      width: 100%;\n      position: absolute;\n      text-align: center;\n      left: 0;\n      bottom: 0;\n      overflow: hidden;\n    }\niframe.powerFrame {\n      width: 500px;\n      height: 300px;\n      transform: scale(0);\n      transform-origin: center;\n      position: absolute;\n      left: 50%;\n      top: 50%;\n      border-style: none;\n    }\n</style>\n<div class=\"powerDiv\">\n    <iframe id=\"frame8675\" class=\"powerFrame\" src=\"/public/img/grafana_icon.svg\" onload=\"scale(this)\">IFRAME not supported by browser.</iframe>\n    <script>\n    document.getElementById('frame8675').parentElement.parentElement.parentElement.style.overflow = 'hidden';\n    </script>\n</div>\n<div class=\"firmwareDiv\">\n  <p class=\"version\" style=\"color:gray; text-align: bottom\">Firmware</p>\n</div>\n<script>\n// Scale Animation when Window is Resized\nfunction scale() {\n  document.querySelectorAll('.powerFrame').forEach(scaled => {\n    parent = scaled.parentNode;\n    ratio = Math.min(1, 1.2 * (parent.offsetWidth / scaled.offsetWidth), (parent.offsetHeight / scaled.offsetHeight));\n    scaled.style.transform = 'translate(-50%, -50%) scale(' + ratio + ')';\n  })\n}\nwindow.addEventListener('resize', function(e){ scale(); }, false);\n\n// Display Firmware Version\nfunction showversion() {\n    var pwver = window.location.protocol + \"//\" + window.location.hostname + \":8675/version\";\n    $.getJSON(pwver, function(data) {\n        var text = `Firmware: ${data.version.split(\" \")[0]}`;\n        $(\".version\").html(text);\n    });\n    setTimeout(showversion, 60000);\n}\nshowversion();\n\n// Load Animation from pyPowerwall\nvar pwurl = window.location.protocol + \"//\" + window.location.hostname + \":8675/\";\ndocument.getElementById('frame8675').src = pwurl;\n</script>"
   }
  },
  {
   "title": "Grid Status",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grid_status\")\r\n  |> aggregateWindow(every: 5m, fn: min, createEmpty: false)\r\n"
    }
   ]
  },
  { "title": "Power Meters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Home Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r._field == \"home\")\r\n  |> integral()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 / 3600.0}))\r\n  |> map(fn: (r) => ({r with _time: now()}))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Solar Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r._field == \"solar\")\r\n  |> integral()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 / 3600.0}))\r\n  |> map(fn: (r) => ({r with _time: now()}))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Solar Energy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r._field == \"home\" or r._field == \"from_grid\")\r\n  |> integral()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 / 3600.0}))\r\n  |> map(fn: (r) => ({r with _time: now()}))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({_time: now(), powered: (r.home - r.from_grid) / r.home}))\r\n"
    }
   ]
  },
  {
   "title": "To Powerwall",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r._field == \"to_powerwall\")\r\n  |> integral()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 / 3600.0}))\r\n  |> map(fn: (r) => ({r with _time: now()}))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "From Powerwall",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r._field == \"from_powerwall\")\r\n  |> integral()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 / 3600.0}))\r\n  |> map(fn: (r) => ({r with _time: now()}))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "To Grid",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r._field == \"to_grid\")\r\n  |> integral()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 / 3600.0}))\r\n  |> map(fn: (r) => ({r with _time: now()}))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "From Grid",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r._field == \"from_grid\")\r\n  |> integral()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 / 3600.0}))\r\n  |> map(fn: (r) => ({r with _time: now()}))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Net Grid Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r._field == \"grid\")\r\n  |> integral()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 / 3600.0}))\r\n  |> map(fn: (r) => ({r with _time: now()}))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  },
  {
   "title": "Savings",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "query": "  from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"from_powerwall\" or r[\"_field\"] == \"solar\" or r[\"_field\"] == \"to_powerwall\" or r[\"_field\"] == \"to_grid\")\r\n  |> sum()\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> pivot(rowKey: [\"_measurement\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with p_h: r.from_powerwall * ${kWhCost}}))\r\n  |> map(fn: (r) => ({r with s_h: (r.solar - (r.to_powerwall + r.to_grid)) * ${kWhCost}}))\r\n  |> map(fn: (r) => ({r with s_g: (r.to_grid) * ${kWhCost}}))\r\n  |> map(fn: (r) => ({r with total: (r.p_h + r.s_h + r.s_g)}))\r\n  |> map(fn: (r) => ({r with \"blank\": (\" \")}))\r\n  |> drop(columns: [\"from_powerwall\", \"to_powerwall\", \"to_grid\", \"solar\"])\r\n"
    }
   ]
  },
  {
   "title": "Self Powered",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"instant_power\")\r\n  |> filter(fn: (r) => r._field == \"solar\" or r._field == \"to_grid\" or r._field == \"to_powerwall\" or r._field == \"from_powerwall\" or r._field == \"from_grid\")\r\n  |> integral()\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0 / 3600.0}))\r\n  |> map(fn: (r) => ({r with _time: now()}))\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({_time: now(), from_solar: ((r.solar) - (r.to_grid) - (r.to_powerwall)), from_powerwall: r.from_powerwall, from_grid: r.from_grid}))\r\n  |> map(fn: (r) => ({r with solar: (1.0 + r.from_solar / math.abs(x: r.from_solar)) * r.from_solar / 2.0 }))\r\n  |> drop(columns: [\"from_solar\"])"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"raw_tesla_energy\")\r\n  |> range(start: -10m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_instant_power\" or r[\"_field\"] == \"load_instant_power\" or r[\"_field\"] == \"site_instant_power\" or r[\"_field\"] == \"solar_instant_power\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"year\", \"host\", \"month\", \"url\"])\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000.0}))"
    }
   ]
  },
  { "title": "Monthly Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Home Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: -1mo, stop: date.truncate(t: now(), unit: 1d))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"home\")\r\n  |> aggregateWindow(every: 1d, fn: sum)\r\n"
    }
   ]
  },
  {
   "title": "Solar Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: -1mo, stop: date.truncate(t: now(), unit: 1d))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\")\r\n  |> aggregateWindow(every: 1d, fn: sum)\r\n"
    }
   ]
  },
  {
   "title": "From Powerwall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: -1mo, stop: date.truncate(t: now(), unit: 1d))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"from_powerwall\")\r\n  |> aggregateWindow(every: 1d, fn: sum)\r\n"
    }
   ]
  },
  {
   "title": "Grid Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: -1mo, stop: date.truncate(t: now(), unit: 1d))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"from_grid\")\r\n  |> aggregateWindow(every: 1d, fn: sum)\r\n"
    },
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: -1mo, stop: date.truncate(t: now(), unit: 1d))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"to_grid\")\r\n  |> map(fn: (r) => ({r with _value: r._value * -1.0}))\r\n  |> aggregateWindow(every: 1d, fn: sum)\r\n\r\n\r\n"
    },
    {
     "query": "import \"date\"\r\nimport \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: -1mo, stop: date.truncate(t: now(), unit: 1d))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grid\")\r\n  |> aggregateWindow(every: 1d, fn: sum)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Solar Energy Year",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: -1y, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\" or r[\"_field\"] == \"home\" or r[\"_field\"] == \"grid\")\r\n  |> aggregateWindow(every: 1d, fn: sum)\r\n"
    }
   ]
  },
  {
   "title": "Solar Energy - Rolling Averages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"date\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> aggregateWindow(every: 1mo, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _field: \"Monthly Average\"}))\r\n  |> map(fn: (r) => ({r with _time: date.sub(d: 15d, from: r._time)}))"
    },
    {
     "alias": "Daily Solar Energy",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n    |> map(fn: (r) => ({r with _field: \"Daily Solar Energy\"}))",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "solar", "operator": ">", "value": "0" }
     ],
     "tz": "America/New_York"
    },
    {
     "alias": "Solar 30-day Average",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> movingAverage(n: 30)\r\n  |> map(fn: (r) => ({r with _field: \"Solar 30-day Average\"}))",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         30
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Solar 12-month Average",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"solar\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> movingAverage(n: 365)\r\n  |> map(fn: (r) => ({r with _field: \"Solar 12-month Average\"}))",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "365" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "Home 30-day Average",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"home\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> movingAverage(n: 30)\r\n  |> map(fn: (r) => ({r with _field: \"Home 30-day Average\"}))",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         30
        ],
        "type": "moving_average"
       }
      ]
     ]
    },
    {
     "alias": "Home 12-month Average",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "http",
     "query": "import \"timezone\"\r\n\r\noption location = timezone.location(name: \"America/Los_Angeles\")\r\n\r\nfrom(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kwh\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"home\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> movingAverage(n: 365)\r\n  |> map(fn: (r) => ({r with _field: \"Home 12-month Average\"}))",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "365" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  { "title": "Powerwall+", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "String Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"strings\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /[A-D][0-99]_Voltage/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "String Current",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"strings\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /[A-D][0-99]_Voltage/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "String Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"strings\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /[A-D][0-99]_Power/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Inverter Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"strings\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /Inverter[0-99]/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "Powerwall Temps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pwtemps\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /PW[0-99]_temp/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vitals\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /ISLAND_Freq/)\r\n  |> filter(fn: (r) => r[\"_value\"] >= 1.0)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n"
    },
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vitals\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PW1_PINV_Fout\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vitals\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /ISLAND_VL[0-3].*/ or r[\"_field\"] =~ /PW[0-99]_PINV_VSplit[1-2]/)\r\n  |> filter(fn: (r) => r[\"_value\"] >= 1.0)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Powerwall Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pods\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /PW[1-99]_POD_nom_full_pack_energy/)\r\n  |> filter(fn: (r) => r[\"_value\"] >= 1.0)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\n\r\n"
    },
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pods\")\r\n  |> filter(fn: (r) => r[\"_field\"] =~ /PW[1-99]_POD_nom_energy_remaining/)\r\n  |> filter(fn: (r) => r[\"_value\"] >= 1.0)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n\r\n\r\n"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Alerts",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "query": "from(bucket: \"tesla_energy\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alerts\")\r\n  |> aggregateWindow(every: 1m, fn: min, createEmpty: true)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"host\", \"month\", \"url\", \"year\"])\r\n\r\n"
    }
   ]
  },
  { "title": "Weather", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Temperature, Humidity, Clouds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "query": "from(bucket: \"raw_weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"feels_like\" or r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"clouds\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Wind, Pressure and Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 108 },
   "targets": [
    {
     "query": "from(bucket: \"raw_weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\" or r[\"_field\"] == \"wind_gust\" or r[\"_field\"] == \"wind_speed\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    },
    {
     "query": "from(bucket: \"raw_weather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"rain_1h\" or r[\"_field\"] == \"snow_1h\")\r\n  |> map(fn: (r) => ({r with _value: r._value * 0.0393701}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}