{
 "title": "Powerwall - Power Flow",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "avg_buy_per_kwh", "label": "Buy Cost per kWh", "query": "${VAR_AVG_BUY_PER_KWH}" },
   { "name": "avg_sell_per_kwh", "label": "Sell Cost per kWh", "query": "${VAR_AVG_SELL_PER_KWH}" },
   { "name": "tz", "label": "Timezone", "query": "${VAR_TZ}" }
  ]
 },
 "panels": [
  { "title": "Live Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Energy Usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Home Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "http",
     "query": "SELECT \"mean_load_instant_power\" FROM \"http\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Solar Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Powerwall",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "http",
     "query": "SELECT max(from_pw) - max(to_pw) FROM autogen.http WHERE $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "from_pw+to_pw" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "${tz:text}"
    },
    {
     "alias": "Grid Usage",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT max(from_grid) - max(to_grid) FROM autogen.http WHERE $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tz": "${tz:text}"
    },
    {
     "alias": "Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT \"mean_percentage\" FROM \"http\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " /0.95 - 5/0.95" ], "type": "math" }
      ]
     ]
    },
    { "target": [ "sun_altitude" ] },
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Clouds",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "clouds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Feels Like",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "feels_like" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid Down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT min(\"grid_status\") +1  FROM \"grid\".\"http\" WHERE grid_status = 0 and $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Reserve",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT \"mean_percentage\" FROM \"http\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "backup_reserve_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Flow",
   "type": "canvas",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "SELECT last(\"load_instant_power\")  AS \"Home\", last(\"solar_instant_power\") AS \"Solar\", last(\"battery_instant_power\") AS \"Battery\", last(\"site_instant_power\") AS \"Grid\", last(\"percentage\") AS \"Percent\" FROM \"raw\".\"http\" WHERE time >= now() - 10m"
    },
    {
     "query": "SELECT last(\"grid_status\")  AS \"Status\" FROM \"raw\".\"http\" WHERE time >= now() - 10m"
    }
   ]
  },
  {
   "title": "Grid Status",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Grid Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT min(\"grid_status\") FROM \"grid\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(previous) tz('${tz:text}')",
     "select": [
      [
       { "params": [ "grid_status" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "${tz:text}"
    },
    {
     "alias": "sync",
     "query": "SELECT min(\"grid_status\") + 2 FROM \"grid\".\"http\" WHERE grid_status = -1 and $timeFilter GROUP BY time($__interval) fill(null) tz('${tz:text}')"
    },
    {
     "alias": "off_grid",
     "query": "SELECT min(\"grid_status\") + 1 FROM \"grid\".\"http\" WHERE grid_status = 0 and $timeFilter GROUP BY time($__interval) fill(null) tz('${tz:text}')"
    }
   ]
  },
  { "title": "Power Meters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Home Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Energy",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "% Solar Powered",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "SolarPowered",
     "measurement": "http",
     "query": "SELECT (home - from_grid) / home FROM \n  (SELECT integral(\"home\")  AS home, integral(\"from_grid\")  AS from_grid \n      FROM \"autogen\".\"http\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "To Powerwall",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "to_pw" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "From Powerwall",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "from_pw" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "To Grid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "to_grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "From Grid",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "from_grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Net Grid Usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "SELECT (integral(\"from_grid\") - integral(\"to_grid\"))   / 1000 / 3600 FROM \"autogen\".\"http\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "from_grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Savings",
   "type": "barchart",
   "description": "Estimated Savings (Buy  = $ $avg_buy_per_kwh / Sell  = $ $avg_sell_per_kwh)",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "powerwall > home",
     "query": "SELECT fp FROM (SELECT sum(\"from_pw\")  * $avg_buy_per_kwh AS fp FROM kwh.http WHERE  $timeFilter )"
    },
    {
     "alias": "solar > home",
     "query": "SELECT s - (tp + tg) FROM (SELECT sum(\"solar\") * $avg_buy_per_kwh AS s,  sum(\"to_pw\")  * $avg_buy_per_kwh AS tp, sum(\"to_grid\") * $avg_buy_per_kwh AS tg FROM kwh.http WHERE  $timeFilter )"
    },
    {
     "alias": "solar > grid",
     "query": "SELECT tgg FROM (SELECT sum(\"to_grid\") * $avg_sell_per_kwh AS tgg FROM kwh.http WHERE  $timeFilter )\n"
    },
    {
     "alias": "total",
     "query": "SELECT tgg + (s - tp - tg ) + fp FROM (SELECT sum(\"to_pw\")  * $avg_buy_per_kwh AS tp, sum(\"solar\") * $avg_buy_per_kwh AS s, sum(\"to_grid\") * $avg_buy_per_kwh AS tg, sum(\"from_pw\") * $avg_buy_per_kwh AS fp, sum(\"to_grid\") * $avg_sell_per_kwh AS tgg FROM kwh.http WHERE  $timeFilter )"
    }
   ]
  },
  {
   "title": "Self-Powered",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "From Solar",
     "query": "SELECT  (1+from_solar/abs(from_solar))*from_solar/2  FROM (SELECT integral(solar)/1000/3600 - (integral(to_pw) - integral(grid_to_pw))/1000/3600  - integral(to_grid)/1000/3600  AS from_solar FROM (SELECT from_solar, solar, to_pw, to_grid, ((from_grid - home - solar) + ABS((from_grid - home - solar))) / 2 AS grid_to_pw FROM autogen.http WHERE  $timeFilter ))"
    },
    {
     "alias": "From Powerwall",
     "measurement": "http",
     "query": "SELECT integral(\"from_pw\")  / 1000 / 3600 FROM \"autogen\".\"http\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "from_pw" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tz": "${tz:text}"
    },
    {
     "alias": "From Grid",
     "measurement": "http",
     "query": "SELECT (integral(from_grid) - integral(grid_to_pw))/1000/3600  AS from_grid FROM (SELECT from_grid, ((from_grid - home - solar) + ABS((from_grid - home - solar))) / 2 AS grid_to_pw FROM autogen.http WHERE  $timeFilter )",
     "select": [
      [
       { "params": [ "from_grid" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000 / 3600" ], "type": "math" }
      ]
     ],
     "tz": "${tz:text}"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "canvas",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "SELECT last(\"load_instant_power\") AS \"Home\", last(\"solar_instant_power\") AS \"Solar\", last(\"battery_instant_power\") AS \"Battery\", last(\"site_instant_power\") AS \"Grid\" FROM \"raw\".\"http\" WHERE time >= now() - 10m"
    },
    {
     "query": "SELECT last(\"load_instant_power\") AS \"Home\", last(\"solar_instant_power\") AS \"Solar\", last(\"battery_instant_power\") AS \"Battery\", last(\"site_instant_power\") AS \"Grid\" FROM \"raw\".\"http\" WHERE time >= now() - 10m"
    }
   ]
  },
  { "title": "Monthly Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Home Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Home Usage",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT sum(\"home\") FROM \"kwh\".\"http\" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('${tz:text}')",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "${tz:text}"
    }
   ]
  },
  {
   "title": "Solar Energy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Solar Energy",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "solar", "operator": ">", "value": "0" }
     ],
     "tz": "${tz:text}"
    }
   ]
  },
  {
   "title": "From Powerwall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "From Powerwall",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "from_pw" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "${tz:text}"
    }
   ]
  },
  {
   "title": "Grid Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "From Grid",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "from_grid" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tz": "${tz:text}"
    },
    {
     "alias": "To Grid",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "to_grid" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tz": "${tz:text}"
    }
   ]
  },
  {
   "title": "Solar Energy Year",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Home Usage",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT sum(\"home\") FROM \"kwh\".\"http\" WHERE (\"home\" > 0) GROUP BY time(1d) fill(null) tz('${tz:text}')",
     "select": [
      [
       { "params": [ "home" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "home", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT sum(\"solar\") FROM \"kwh\".\"http\" WHERE (\"solar\" > 0) GROUP BY time(1d) fill(null) tz('${tz:text}')",
     "select": [
      [
       { "params": [ "solar" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "solar", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Grid Usage",
     "query": "SELECT sum(\"from_grid\") - sum(\"to_grid\") as \"grid\" FROM \"kwh\".\"http\" WHERE  $timeFilter GROUP BY time(1d) fill(null) tz('${tz:text}')"
    }
   ]
  },
  { "title": "Powerwall+ String Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  { "title": "System Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "home_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "grid_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Powerwall",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "pw_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Home",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "home_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "grid_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Powerwall",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "pw_current" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Powerwall Capacity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "PW1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW1_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW2_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW3_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW4_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW5_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW6_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW7_POD_nom_full_pack_energy\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW7_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW8_POD_nom_full_pack_energy\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW8_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW9_POD_nom_full_pack_energy\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW9_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW10_POD_nom_full_pack_energy\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW10_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW11_POD_nom_full_pack_energy\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW11_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW12_POD_nom_full_pack_energy\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW12_POD_nom_full_pack_energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW1 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW1_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW2 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW2_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW3 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW3_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW4 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW4_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW5 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW5_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW6 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW6_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW7 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW7_POD_nom_energy_remaining\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW7_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW8 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW8_POD_nom_energy_remaining\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW8_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW9 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW9_POD_nom_energy_remaining\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW9_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW10 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW10_POD_nom_energy_remaining\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW10_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW11 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW11_POD_nom_energy_remaining\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW11_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW12 Charge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW12_POD_nom_energy_remaining\") FROM \"pod\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW12_POD_nom_energy_remaining" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "Home L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "ISLAND_FreqL1_Load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Home L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "ISLAND_FreqL2_Load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "ISLAND_FreqL1_Main" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "ISLAND_FreqL2_Main" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW1_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW2_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW3_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW4_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW5_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW6_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW7_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW8_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW9_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW10_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW11_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "PW12_PINV_Fout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Off Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT min(\"grid_status\") +1 FROM \"grid\".\"http\" WHERE (\"grid_status\" = 0) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "grid_status" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "grid_status", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Off Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "grid_status" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "grid_status", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Home L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"ISLAND_VL1N_Load\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ISLAND_VL1N_Load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Home L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "ISLAND_VL2N_Load" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"METER_X_VL1N\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ISLAND_VL1N_Main" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Grid L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "ISLAND_VL2N_Main" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW1 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW1_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW1_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW1 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW1_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW1_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW2 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW2_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW2_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW2 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW2_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW2_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW3 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW3_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW3_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW3 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW3_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW3_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW4 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW4_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW4_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW4 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW4_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW4_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW5 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW5_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW5_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW5 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW5_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW5_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW6 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW6_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW6_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW6 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW6_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW6_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW7 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW7_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW7_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW7 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW7_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW7_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW8 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW8_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW8_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW8 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW8_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW8_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW9 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW9_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW9_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW9 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW9_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW9_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW10 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW10_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW10_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW10 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW10_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW10_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW11 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW11_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW11_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW11 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW11_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW11_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW12 L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW12_PINV_VSplit1\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW12_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW12 L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW12_PINV_VSplit2\") FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" < 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW12_PINV_VSplit2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW1_PINV_VSplit1\") +  mean(\"PW1_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW1_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW2_PINV_VSplit1\") +  mean(\"PW2_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW2_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW3_PINV_VSplit1\") +  mean(\"PW3_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW3_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW4_PINV_VSplit1\") +  mean(\"PW4_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW4_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW5_PINV_VSplit1\") +  mean(\"PW5_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW5_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW6_PINV_VSplit1\") +  mean(\"PW6_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW6_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW7_PINV_VSplit1\") +  mean(\"PW7_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW7_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW8_PINV_VSplit1\") +  mean(\"PW8_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW8_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW9_PINV_VSplit1\") +  mean(\"PW9_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW9_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW10_PINV_VSplit1\") +  mean(\"PW10_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW10_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW11_PINV_VSplit1\") +  mean(\"PW11_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW11_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"PW12_PINV_VSplit1\") +  mean(\"PW12_PINV_VSplit2\")  FROM \"vitals\".\"http\" WHERE \"ISLAND_VL1N_Load\" > 200.0 AND  $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "PW12_PINV_VSplit1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "PW1",
     "query": "SELECT mean(\"PW1_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PW2",
     "query": "SELECT mean(\"PW2_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PW3",
     "query": "SELECT mean(\"PW3_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PW4",
     "query": "SELECT mean(\"PW4_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PW5",
     "query": "SELECT mean(\"PW5_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PW6",
     "query": "SELECT mean(\"PW6_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PW7",
     "query": "SELECT mean(\"PW7_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PW8",
     "query": "SELECT mean(\"PW8_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PW9",
     "query": "SELECT mean(\"PW9_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PW10",
     "query": "SELECT mean(\"PW10_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PW11",
     "query": "SELECT mean(\"PW11_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "PW12",
     "query": "SELECT mean(\"PW12_v_out\") FROM \"vitals\".\"http\" WHERE $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Grid Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT min(\"grid_status\") +1 FROM \"grid\".\"http\" WHERE (\"grid_status\" = 0) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "grid_status" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "+1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "grid_status", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Alerts",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT *::field from alerts.alerts where $timeFilter"
    }
   ]
  },
  { "title": "Weather", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Temperature, Humidity and Clouds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Humidity (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Clouds (%)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "clouds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Feels Like",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "feels_like" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind, Pressure and Precipitation ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Snow",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "snow_1h" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Rain",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "rain_1h" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Visibility (K)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "visibility" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Wind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}